### PR TITLE
EnumFilter: Display the value returned by the method defined in "property"

### PR DESCRIPTION
**Pull request by AndreSchwarzer**
Display the value returned by the method defined in "property"

Similar to https://github.com/datomatic/nova-enum-field/pull/1

### CODE REVIEW

**Comment by AndreSchwarzer** [comment]
# Code
In the Nova resource:

```php
    public function filters(NovaRequest $request): array
    {
        return [
            EnumBooleanFilter::make('payment', PaymentMethod::class)
                ->name(__('Zahlungsart'))
                ->property('label'),
        ];
    }
```

The ENUM:

```php
enum PaymentMethod: string
{
    case SpkSepa = 'sparkasse-sepa';
    case SpkWire = 'sparkasse-wire';
    case BwStripeCC = 'billwerk-stripe-cc';
    case BwPayPal = 'billwerk-paypal';

    public function label(): string
    {
        return match ($this) {
            self::SpkSepa => __('Lastschrift'),
            self::SpkWire => __('Überweisung'),
            self::BwStripeCC => __('Kreditkarte'),
            self::BwPayPal => __('PayPal'),
        };
    }
}
```

# How it's displayed

| Before | After |
| ------ | ------ |
| Screenshot 2023-08-07 at 10 49 22 | Screenshot 2023-08-07 at 10 49 06 |

**Comment by AndreSchwarzer** [comment]
Hey @trippo and @Synchro

is there anything further I can provide for you to get this merged?

**Comment by Synchro** [comment]
I don't have commit rights here, so nothing I can do. Do you need this though? I use a label function like that, and I set up my fields like this to use it:

```php
            Enum::make('Type')
                ->attach(CustomerType::class)
                ->options(CustomerType::options())
                ->default(CustomerType::CUSTOMER)
                ->displayUsingLabels()
                ->filterable(),
```
I think `displayUsingLabels()` is what you're looking for. The `options()` method you see on my enum is a trait that looks like this:

```php
declare(strict_types=1);

namespace App\Enums;

trait HasOptions
{
    /**
     * Gather all the values of an Enum and return an array of values and labels suitable for populating select elements
     *
     * @return array
     */
    public static function options(): array
    {
        $options = [];
        foreach (self::cases() as $case) {
            $options[$case->value] = $case->label();
        }
        return $options;
    }
}
```

`displayUsingLabels()` is used when displaying the field normally, and `options()` is used when editing or creating, so you need both.

**Comment by trippo** [comment]
Thanks

**Comment by AndreSchwarzer** [comment]
Hey @Synchro thanks for your suggestion.

I encountered the same issue like I had in https://github.com/datomatic/nova-enum-field/pull/1 with the Filters. The `property` parameter wasn't used throughout every step/in every place.

With this PR I fixed it for Filters.

**Pull request merged**
